export const ADD_TO_CART='ADD_TO_CART';
export const REMOVE_ITEM='REMOVE_ITEM';
export const REDUCE_ITEM='REDUCE_ITEM';
export const ADD_LOCAL_STORAGE='ADD_LOCAL_STORAGE';
export const CLEAR_ALL_ITEM='CLEAR_ALL_ITEM';

